services:
  - type: web
    name: medical-chatbot
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: PINECONE_API_KEY
        value: your_pinecone_key
      - key: HUGGINGFACEHUB_API_TOKEN
        value: your_hf_token